<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>HER (HTML Embedded Ruby)</string>
  <key>scopeName</key>
  <string>text.html.her</string>
  <key>fileTypes</key>
  <array>
    <string>her</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#template-comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#html-comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#doctype</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#component-tag</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#html-tag</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#hole</string>
    </dict>
    <dict>
      <key>include</key>
      <string>text.html.basic</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>template-comment</key>
    <dict>
      <key>name</key>
      <string>comment.block.her</string>
      <key>begin</key>
      <string>&lt;%#</string>
      <key>end</key>
      <string>%&gt;</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.begin.her</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.comment.end.her</string>
        </dict>
      </dict>
    </dict>
    <key>html-comment</key>
    <dict>
      <key>name</key>
      <string>comment.block.html</string>
      <key>begin</key>
      <string>&lt;!--</string>
      <key>end</key>
      <string>--&gt;</string>
    </dict>
    <key>doctype</key>
    <dict>
      <key>name</key>
      <string>meta.tag.metadata.doctype.html</string>
      <key>match</key>
      <string>&lt;![^&gt;]*&gt;</string>
    </dict>
    <key>hole</key>
    <dict>
      <key>name</key>
      <string>meta.embedded.block.ruby.her</string>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>\}</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.begin.her</string>
        </dict>
      </dict>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.section.embedded.end.her</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nested-braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.ruby</string>
        </dict>
      </array>
    </dict>
    <key>nested-braces</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>end</key>
      <string>\}</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#nested-braces</string>
        </dict>
        <dict>
          <key>include</key>
          <string>source.ruby</string>
        </dict>
      </array>
    </dict>
    <key>component-tag</key>
    <dict>
      <key>name</key>
      <string>meta.tag.component.her</string>
      <key>begin</key>
      <string>(&lt;/?)((?:\.[a-z_][a-zA-Z0-9_]*)|(?::[a-z_][a-zA-Z0-9_]*)|(?:[A-Z][a-zA-Z0-9_]*(?:::[A-Z][a-zA-Z0-9_]*)*\.[a-z_][a-zA-Z0-9_]*))</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.begin.her</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.tag.component.her support.class.component.her</string>
        </dict>
      </dict>
      <key>end</key>
      <string>/?&gt;</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.end.her</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#tag-innards</string>
        </dict>
      </array>
    </dict>
    <key>html-tag</key>
    <dict>
      <key>name</key>
      <string>meta.tag.html.her</string>
      <key>begin</key>
      <string>(&lt;/?)([a-z][a-zA-Z0-9-]*)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.begin.html</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.tag.html</string>
        </dict>
      </dict>
      <key>end</key>
      <string>/?&gt;</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.end.html</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#tag-innards</string>
        </dict>
      </array>
    </dict>
    <key>tag-innards</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#hole</string>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.double.html</string>
          <key>begin</key>
          <string>"</string>
          <key>end</key>
          <string>"</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#hole</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>string.quoted.single.html</string>
          <key>begin</key>
          <string>'</string>
          <key>end</key>
          <string>'</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#hole</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>name</key>
          <string>entity.other.attribute-name.her</string>
          <key>match</key>
          <string>[a-zA-Z_:@][-a-zA-Z0-9_:.?!]*</string>
        </dict>
        <dict>
          <key>name</key>
          <string>punctuation.separator.key-value.html</string>
          <key>match</key>
          <string>=</string>
        </dict>
      </array>
    </dict>
  </dict>
</dict>
</plist>
